{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if .Values.service.neg }}
    {{- range .Values.image.ports }}
    cloud.google.com/neg: '{"exposed_ports": {"{{ .externalPort }}":{}}}'
    {{- end}}
    {{- end }}
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.deploymentName }}
  labels:
    projectName: {{ .Values.deploymentName }}
    environment: {{ .Values.environment }}
    type: service
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range  $port := .Values.ports }}
    - name: {{$port.name}}
      targetPort: {{$port.containerPort}}
      port: {{$port.containerPort}}
      protocol: {{$port.protocol}}
  {{- end}}
  selector:
    projectName: {{ .Values.deploymentName }}
    environment: {{ .Values.environment }}
    type: deployment
{{- end }}