{{- if .Values.ports -}}
{{- if (index .Values.ports 0).containerPort -}}
{{- if $.Values.ingress }}
{{- if $.Values.ingress.domain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.deploymentName }}-ingress
  namespace: {{ $.Values.deploymentName }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    {{- if $.Values.ingress }}
    {{- if $.Values.ingress.domain }}
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{ .Values.ingress.certificateName }}
    appgw.ingress.kubernetes.io/ssl-redirect: true
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.appDomain }}"
    external-dns.alpha.kubernetes.io/alias: "true"
    {{- end}}
    {{- end}}
spec:
{{- $len := len $.Values.ports }}
{{- if eq $len 1 }}
  defaultBackend:
    service:
      name: {{ $.Values.deploymentName }}
      {{- range  $index,$port := $.Values.ports }}
      {{- if eq $index  0}}
      port:
        number: {{ $port.containerPort}}
      {{- end}}
      {{- end}}
{{- else}}
  rules:
  - http:
      paths:
      {{- range $index,$port := $.Values.ports }}
      - path: /{{$port.name}}/*
        backend:
          service:
            name: {{ $.Values.deploymentName }}
            port: 
              number: {{ $port.containerPort}}
      {{- end}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}