{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.applicationName }}-secret-env
  namespace: {{ $.Values.applicationName }}
type: opaque
data:
  {{- range $key,$val := .Values.secrets }}
  {{$key}}: {{$val | b64enc}}
  {{- end}}
{{- end}}
